---

- name: Update System Information
  uri:
    url: "{{ jumpcloud_api_v1_url }}/systems/{{ jumpcloud_system_key.stdout }}"
    method: PUT
    headers:
      "Content-Type": "application/json"
      "Accept":       "application/json"
      "x-api-key":    "{{ jumpcloud_api_key }}"
    body_format:  json
    body: '{ "displayName" : "{{ jumpcloud_displayName }}",
    "allowPublicKeyAuthentication" : "{{ jumpcloud_allowPublicKeyAuthentication }}",
    "allowSshPasswordAuthentication" : "{{ jumpcloud_allowSshPasswordAuthentication }}",
    "allowSshRootLogin" : "{{ jumpcloud_allowSshRootLogin }}",
    "allowMultiFactorAuthentication" : "{{ jumpcloud_allowMultiFactorAuthentication }}" }'
    follow_redirects: all
    return_content: yes
    status_code: 200
  delegate_to: localhost
  register: http_outcome
  when: jumpcloud_system_key is defined
...
